#!/bin/bash

docker run \
  --rm \
  --name rebase-labs \
  -v $(pwd):/app \
  -w /app \
  -p 3000:3000 \
  --network rebase-labs \
  ruby \
  bash -c "bundle install && ruby server.rb"


# version: '3.9'
# services: 
#   app: 
#     image:'ruby'
#     working_dir: /app
#     volumes:
#     - :/app
#     - rubygems:/usr/local/bundle
#   ports:
#   - "3000:3000"
  
#   volumes:
#     rubygems: 

